services:
  pandaplan:
    build: .
    container_name: pandaplan
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    networks:
      - swag
    env_file: ".env"
networks:
  swag:
    name: swag_network
    external: true
